name: 'Stata Action'
description: 'Run Stata do-file using GitHub Actions'
author: 'Lukman Edwindra'
inputs:
  program:
    required: true
    description: 'Your Stata codefile'
    default: 'main.do'
  version:
    required: true
    description: 'Your Stata version'
  serial-number:
    required: true
    description: 'Your Stata serial number (this will be encrypted so that nobody can see it)'
  code:
    required: true
    description: 'Your Stata code license (this will be encrypted so that nobody can see it)'
  authorization:
    required: true
    description: 'Your Stata authorization license (this will be encrypted so that nobody can see it)'
  name:
    required: true
    description: 'Your name to be displayed in Stata license'
  institution:
    required: true
    description: 'Your institution to be displayed in Stata license'
  changedir:
    required: false
    default: 'yes'
    description: 'Should the working directory be changed to the file location being run (cd dir ; stata prog.do) or not (stata dir/prog.do). Affects environment for Stata'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.program }}
    - ${{ inputs.version }}
    - ${{ inputs.serial-number }}
    - ${{ inputs.code }}
    - ${{ inputs.authorization }}
    - ${{ inputs.name }}
    - ${{ inputs.institution }}
    - ${{ inputs.changedir }}