name: Test CI Stata

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Stata Action
      id: ci-stata
      uses: labordynamicsinstitute/continuous-integration-stata@v0.1
      with:
        program: test/run.do
        version: ${{ secrets.STATA_VERSION }}
        serial-number: ${{ secrets.STATA_SERIALNUMBER }}
        code: ${{ secrets.STATA_CODE }}
        authorization: ${{ secrets.STATA_AUTH }}
        first-name: ${{ secrets.STATA_FIRST_NAME }}
        last-name: ${{ secrets.STATA_LAST_NAME }}
